apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wda-ui-pod
  name: wda-ui-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wda-ui-pod
  template:
    metadata:
      labels:
        app: wda-ui-pod
    spec:
      containers:
        - image: nandinikarthik14/wda-ui:latest
          name: wda-ui
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: wda-svc
  labels:
    app: wda-svc
spec:
  type: NodePort
  selector:
    app: wda-ui-pod
  ports:
    - protocol: TCP
      nodePort: 31321
      port: 5000
      targetPort: 5000